#!/usr/bin/env python3

from PaStA.PatchStack import format_date_ymd
from PaStA import patch_stack_list

from config import *


def analyse_num_commits():
    for header, patch_stack_group in patch_stack_list.iter_groups():
        data = []
        for patch_stack in patch_stack_group:
            data.append('"%s" %s "%s" %s %d' % (patch_stack.stack_version,
                                                format_date_ymd(patch_stack.stack_release_date),
                                                patch_stack.base_version,
                                                format_date_ymd(patch_stack.base_release_date),
                                                patch_stack.num_commits()))

        with open(COMMITCOUNT_PREFIX + PROJECT_NAME + '-' + header, 'w') as f:
            f.write('stackVersion stackReleaseDate baseVersion baseReleaseDate numCommits\n')
            f.write("\n".join(data) + '\n')


def main():
    # Create destination directory if not existing
    if not os.path.exists(COMMITCOUNT_PREFIX):
        os.makedirs(COMMITCOUNT_PREFIX)

    # Run analyse_num_commits on the patchstack
    analyse_num_commits()


if __name__ == '__main__':
    main()
