#!/usr/bin/env python3

import sys

from PaStA.PatchEvaluation import preevaluate_single_patch, evaluate_single_patch, compare_hashes, getch
from PaStA import config

def compare_patches(commits):
    for i in range(len(commits)-1):
        commit_a = commits[i]
        commit_b = commits[i+1]

        compare_hashes(commit_a, commit_b)

        rating = preevaluate_single_patch(commit_a, commit_b)
        if rating:
            print('Preevaluation: Possible candidates')
            rating = evaluate_single_patch(config.thresholds, commit_a, commit_b)
            print(str(rating.msg_rating) + ' message and ' +
                  str(rating.diff_rating) + ' diff, diff length ratio: ' +
                  str(rating.diff_length_ratio))
        else:
            print('Preevaluation: Not related')
        getch()

if __name__ == '__main__':
    compare_patches(sys.argv[1:])
