#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
 sudo chmod u+x maintainers 
"""

import errno
import logging
import sys

from pypasta.LinuxMaintainers import LinuxMaintainers

log = logging.getLogger('PaStA')


def usage(me, exit_code=errno.EINVAL):
    print("usage:")
    if exit_code != 0:
        file = sys.stderr


def main(argv):
    print("test")
    print(argv)
    me = argv.pop(0)
    print(me, argv)

    while len(argv) and argv[0].startswith('-'):
        argument = argv.pop(0)

        if argument == '-c':
            if not argv:
                usage(me)
            config = argv.pop(0)
        elif argument == '-d':
            level = logging.DEBUG
            debug = True

    if not argv:
        usage(me)
    print("argv", argv)

    sub = argv.pop(0)
    if sub == '-h' or sub == '--help':
        usage(me, 0)
    elif sub == 'show':
        print("show")
        print("argv", argv)
        display_maintainers(argv)
    else:
        print('Unknown command: %s' % sub)
        usage(me)


if __name__ == '__main__':
    log.info('Shutting down')
    sys.exit(0)
'''
from string import upper
mylis=['this is test', 'another test']

filter(upper, mylis)
['this is test', 'another test']
'''

def display_maintainers(filenames):
    print(filenames)
    maintainers = open('/resources/linux/repo/MAINTAINERS', 'r').read()
    maintain = LinuxMaintainers(maintainers)
    subsystems = maintain.get_subsystems_by_files(filenames)
    
    for filename in filenames:
        subsystem = subsystems.pop()
        maintainer = maintain.get_maintainers(subsystems)
        print(filename, subsystem, maintainer)

    
