#!/bin/bash

# Copyright (c) OTH Regensburg, 2016
#
# Author:
#   Ralf Ramsauer <ralf.ramsauer@othr.de>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.

cd PaStA-resources
./prepare_projects $1
