#!/usr/bin/env python3

import sys
from bin.pasta_analyse import analyse
from bin.pasta_compare import compare
from bin.pasta_rate import rate
from bin.pasta_statistics import statistics
from bin.pasta_compare_stacks import compare_stacks
from bin.pasta_patch_descriptions import patch_descriptions
from bin.pasta_upstream_history import pasta_upstream_history


def usage(me):
    print('usage: %s sub -h\n'
          'where sub is one of:\n'
          '  analyse\n'
          '  compare\n'
          '  rate\n'
          '  statistics\n'
          '  compare_stacks\n'
          '  patch_descriptions\n'
          '  upstream_history' % me)
    quit()


def main(argv):
    me = argv[0]
    if len(argv) < 2:
        usage(me)

    sub = argv[1]
    args = argv[2:]

    if sub == '-h':
        usage(me)
    elif sub == 'analyse':
        analyse(sub, args)
    elif sub == 'compare':
        compare(args)
    elif sub == 'rate':
        rate(sub, args)
    elif sub == 'statistics':
        statistics(sub, args)
    elif sub == 'compare_stacks':
        compare_stacks(sub, args)
    elif sub == 'patch_descriptions':
        patch_descriptions(sub, args)
    elif sub == 'upstream_history':
        pasta_upstream_history(sub, args)
    else:
        print('Unknown command: %s' % sub)
        usage(me)

if __name__ == '__main__':
    main(sys.argv)
