#!/bin/bash

function die {
  echo "$@" 1>&2;
  exit -1;
}

echo "This may take a while. Take a cup of coffe. Really."

git submodule update --init || die "submodule update failed"

cd PaStA-resources
./prepare_projects
