#!/usr/bin/env python3

import argparse
import os
from subprocess import call

from PaStA import *


def release_dates(mainline_release_dates_filename, stack_release_dates_filename):
    stacks = dict()
    base = dict()

    for group_name, stacks_in_group in patch_stack_definition.iter_groups():
        for stack in stacks_in_group:
            stacks[stack.stack_version] = group_name, stack.stack_release_date
            base[stack.base_version] = stack.base_release_date

    with open(mainline_release_dates_filename, 'w') as f:
        f.write('Version ReleaseDate\n')
        for version, date in base.items():
            f.write('%s %s\n' %
                    (version, format_date_ymd(date)))

    with open(stack_release_dates_filename, 'w') as f:
        f.write('VersionGroup Version ReleaseDate\n')
        for version, (group, date) in stacks.items():
            f.write('%s %s %s\n' % (group,
                                    version,
                                    format_date_ymd(date)))


def upstream_analysis(upstream_filename, patches_filename, occurrence_filename, patch_groups, date_selector):
    upstream = open(upstream_filename, 'w')
    patches = open(patches_filename, 'w')
    occurrence = open(occurrence_filename, 'w')

    # Write CSV Headers
    upstream.write('PatchGroup UpstreamHash UpstreamCommitDate FirstStackOccurence\n')
    patches.write('PatchGroup CommitHash StackVersion BaseVersion\n')
    occurrence.write('PatchGroup OldestVersion LatestVersion FirstReleasedIn LastReleasedIn\n')

    cntr = 0
    for group in patch_groups:
        cntr += 1

        # write stack patches
        for patch in group:
            stack_of_patch = patch_stack_definition.get_stack_of_commit(patch)
            stack_version = stack_of_patch.stack_version
            base_version = stack_of_patch.base_version
            patches.write('%d %s %s %s\n' % (cntr, patch, stack_version, base_version))

        # optional: write upstream information
        if group.property:
            commit = get_commit(group.property)

            first_stack_occurence = min(map(date_selector, group))

            upstream.write('%d %s %s %s\n' % (cntr,
                                              commit.commit_hash,
                                              format_date_ymd(commit.commit_date),
                                              format_date_ymd(first_stack_occurence)))

        # Patch occurrence
        latest_version = oldest_version = patch_stack_definition.get_stack_of_commit(group[0])
        first_released = last_released = date_selector(group[0]), patch_stack_definition.get_stack_of_commit(group[0])

        for patch in group[1:]:
            # Get stack of current patch
            stack = patch_stack_definition.get_stack_of_commit(patch)

            # Check latest version
            if patch_stack_definition.is_stack_version_greater(stack, latest_version):
                latest_version = stack

            # Check oldest version
            if not patch_stack_definition.is_stack_version_greater(stack, oldest_version):
                oldest_version = stack

            # Check first released in
            if date_selector(patch) < first_released[0]:
                first_released = date_selector(patch), stack

            # Check last released in
            if date_selector(patch) > last_released[0]:
                last_released = date_selector(patch), stack

        latest_version = latest_version.stack_version
        oldest_version = oldest_version.stack_version

        first_released = first_released[1].stack_version
        last_released = last_released[1].stack_version

        occurrence.write('%d %s %s %s %s\n' % (cntr,
                                               oldest_version, latest_version,
                                               first_released, last_released))

    upstream.close()
    patches.close()
    occurrence.close()


def release_sort(release_sort_filename):
    with open(release_sort_filename, 'w') as f:
        f.write('VersionGroup Version\n')
        for version_group, stacks in patch_stack_definition.iter_groups():
            for stack in stacks:
                f.write('%s %s\n' % (version_group, stack.stack_version))


def main():
    parser = argparse.ArgumentParser(description='Interactive Rating: Rate evaluation results')
    parser.add_argument('-pg', dest='pg_filename', metavar='filename',
                        default=config.patch_groups, help='Patch group file')
    parser.add_argument('-R', dest='r_resources', metavar='directory',
                        default=config.R_resources, help='Output directory for R resources')
    parser.add_argument('-ds', dest='date_selector', default='SRD', choices=['SRD', 'CD'],
                        help='Date selector: Either Commit Date or Stack Release Date (default: %(default)s)')
    parser.add_argument('-noR', dest='R', action='store_false', help='Don\'t invoke R')
    parser.set_defaults(R=True)
    args = parser.parse_args()

    patch_groups = EquivalenceClass.from_file(args.pg_filename, must_exist=True)

    r_resources = args.r_resources
    if not os.path.exists(r_resources):
        os.makedirs(r_resources)

    release_sort_filename = os.path.join(r_resources, "release-sort")
    mainline_release_dates_filename = os.path.join(r_resources, 'mainline-release-dates')
    stack_release_dates_filename = os.path.join(r_resources, 'stack-release-dates')
    patches_filename = os.path.join(r_resources, 'patches')
    upstream_filename = os.path.join(r_resources, 'upstream')
    occurrence_filename = os.path.join(r_resources, 'patch-occurrence')

    if args.date_selector == 'SRD':
        date_selector = lambda x: patch_stack_definition.get_stack_of_commit(x).stack_release_date
    elif args.date_selector == 'CD':
        date_selector = lambda x: get_commit(x).commit_date
    else:
        raise NotImplementedError('Unknown date selector: ' % args.date_selector)

    # Write upstream occurence file
    upstream_analysis(upstream_filename,
                      patches_filename,
                      occurrence_filename,
                      patch_groups, date_selector)

    # Write release dates file
    release_dates(mainline_release_dates_filename,
                  stack_release_dates_filename)

    # Write release sort file
    release_sort(release_sort_filename)

    if args.R:
        call(['./R/PaStA.R',
              config.project_name,
              r_resources,
              release_sort_filename,
              mainline_release_dates_filename,
              stack_release_dates_filename,
              patches_filename,
              upstream_filename,
              occurrence_filename])

if __name__ == '__main__':
    main()
