"""
PaStA - Patch Stack Analysis

Copyright (c) OTH Regensburg, 2021

Author:
  Ralf Ramsauer <ralf.ramsauer@oth-regensburg.de>

This work is licensed under the terms of the GNU GPL, version 2.  See
the COPYING file in the top-level directory.
"""

from .MailCharacteristics import MailCharacteristics, PatchType


class XenMailCharacteristics(MailCharacteristics):
    ROOT_DIRS = ['.github/',
                 'BitKeeper/',
                 'buildconfigs/',
                 'config/',
                 'docs/',
                 'extras/',
                 'freebsd-5.3-xen-sparse/',
                 'LICENSES/',
                 'linux-2.4-xen-sparse/',
                 'linux-2.4.26-xen-sparse/',
                 'linux-2.4.29-xen-sparse/',
                 'linux-2.4.30-xen-sparse/',
                 'linux-2.6-xen-sparse/',
                 'linux-2.6.7-xen-sparse/',
                 'linux-2.6.10-xen-sparse/',
                 'linux-2.6.11-xen-sparse/',
                 'm4/',
                 'misc/',
                 'mini-os/',
                 'netbsd-2.0-xen-sparse/',
                 'old/',
                 'patches/',
                 'scripts/',
                 'stubdom/',
                 'automation/',
                 'tools/',
                 'unmodified_drivers/',
                 'xen/',
                 'xen-2.4.16/',
                 'xenolinux-2.4.16-sparse/',
                 'xenolinux-2.4.21-pre4-sparse/',
                 'xenolinux-2.4.21-sparse/',
                 'xenolinux-2.4.22-sparse/',
                 'xenolinux-2.4.23-sparse/',
                 'xenolinux-2.4.24-sparse/',
                 'xenolinux-2.4.25-sparse/',
                 'xenolinux-2.4.26-sparse/',
                 '~/',
    ]
    ROOT_FILES = ['.bk-to-hg',
                  '.cirrus.yml',
                  '.gitarchive-info',
                  '.gitattributes',
                  '.gitignore',
                  '.gitlab-ci.yml',
                  '.hg-to-bk',
                  '.hgignore',
                  '.hgsigs',
                  '.hgtags',
                  '.readthedocs.yaml',
                  '.rootkeys',
                  '.travis.yml',
                  'CHANGELOG.md',
                  'CODING_STYLE',
                  'CONTRIBUTING',
                  'COPYING',
                  'CREDITS',
                  'Config.mk',
                  'INSTALL',
                  'MAINTAINERS',
                  'Makefile',
                  'README',
                  'README.CD',
                  'SUPPORT.md',
                  'TODO',
                  'autogen.sh',
                  'config.guess',
                  'config.sub',
                  'configure',
                  'configure.ac',
                  'install.sh',
                  'version.sh',
    ]

    HAS_MAINTAINERS = True

    # Additional lists that are not known by pasta
    LISTS = {'advisory-board@lists.xen.org',
             'advisory-board@lists.xenproject.org',
             'amd-xen-safety@groups.io',
             'committers@xenproject.org',
             'coverity@xenproject.org',
             'embedded-pv-devel@lists.xenproject.org',
             'embeddedxen-devel@lists.sourceforge.net',
             'freebsd-xen@freebsd.org',
             'fusa-sig@lists.xenproject.org',
             'infra@xenproject.org',
             'ltc-xen-fullvirt@linux.ibm.com',
             'minios-devel@lists.xen.org',
             'minios-devel@lists.xenproject.org',
             'mirageos-devel@lists.xenproject.org',
             'osstest-admin@xenproject.org',
             'osstest-output@lists.xenproject.org',
             'osstest@xenbits.xen.org',
             'pkg-xen-devel@lists.alioth.debian.org',
             'port-xen@netbsd.org',
             'publicity@lists.xenproject.org',
             'security@xen.org',
             'security@xenproject.org',
             'technical-coordination-team@lists.xenproject.org',
             'unikraft-devel@lists.xenproject.org',
             'win-pv-devel@lists.xenproject.org',
             'wg-test-framework@lists.xenproject.org',
             'xapi@lists.xenproject.org',
             'xapi-devel@lists.xenproject.org',
             'xci-devel@lists.xen.org',
             'xci-devel@lists.xensource.com',
             'xen-announce@lists.sourceforge.net',
             'xen-announce@lists.xen.org',
             'xen-announce@lists.xensource.com',
             'xen-announce@lists.xenproject.org',
             'xen-api@lists.xen.org',
             'xen-api@lists.xenproject.org',
             'xen-api@lists.xensource.com',
             'xen-arm@lists.xen.org',
             'xen-arm@lists.xensource.com',
             'xen-arm@lists.xenproject.org',
             'xen-bugs@lists.xensource.com',
             'xen-changelog@lists.xensource.com',
             'xen-changelog@lists.xenproject.org',
             'xen-community@lists.xensource.com',
             'xen-devel@lists.sf.net',
             'xen-devel@lists.sourceforge.net',
             'xen-devel@lists.xen.org',
             'xen-devel@lists.xensource.com',
             'xen-devel@nongnu.org',
             'xen-discuss@opensolaris.org',
             'xen-ia64@lists.xensource.com',
             'xen-ia64-devel@lists.xen.org',
             'xen-ia64-devel@lists.xensource.com',
             'xen-merge@lists.xensource.com',
             'xen-ppc-devel@lists.xensource.com',
             'xen-research@lists.xensource.com',
             'xen-security-issues@lists.xen.org',
             'xen-security-issues-discuss@lists.xen.org',
             'xen-security-issues-discuss@lists.xenproject.org',
             'xen-staging@lists.xensource.com',
             'xen-tools@lists.xensource.com',
             'xen-tools@packages.debian.org',
             'xen-users@lists.xen.org',
             'xen-users@lists.xensource.com',
             'xen-users@lists.xenproject.org',
             'xen-users@xenproject.org',
             'xen-xapl@lists.xenproject.org',
             'xen-xci@lists.xen.org',
             'xen@lists.fedoraproject.org',
             'xense-devel@lists.xensource.com',
             'xs-devel@lists.xen.org',
             'xs-devel@lists.xenserver.org',
    }

    def __init__(self, repo, maintainers_version, clustering, message_id):
        super().__init__(repo, clustering, message_id)
        self.__init()
        self._cleanup(maintainers_version)

    def __init(self):
        pass
